site_name: DetranGO

repo_name: "2023.1-DetranGO"
repo_url: "https://github.com/Interacao-Humano-Computador/2023.1-DetranGO"

theme:
  name: material
  logo: assets/DETRAN/detran-icon.svg
  favicon: assets/DETRAN/detran-icon.svg
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs

nav:
    - Home: index.md
    - Reuniões:
          - Reunião 1: reunioes/reuniao1.md
          - Reunião 2: reunioes/reuniao2.md
          - Reunião 3: reunioes/reuniao3.md
          - Reunião 4: reunioes/reuniao4.md
          - Reunião 5: reunioes/reuniao5.md
    - Planejamento:
          - Reuniões: planejamento/reunioes.md
          - Cronograma: planejamento/cronograma.md
          - Cronograma Executado: planejamento/cronograma_executado.md
          - Metodologias: planejamento/metodologia.md
          - Ferramentas: planejamento/ferramentas.md
          - Sítios Avaliados:
                - Sítios Avaliados: planejamento/sites_avaliados/sites_avaliados.md
                - Avaliação NFE: planejamento/sites_avaliados/avaliacao_NFE.md
                - Avaliação SAAE: planejamento/sites_avaliados/avaliacao_SAAE.md
                - Avaliação CAESB: planejamento/sites_avaliados/avaliacao_CAESB.md
                - Avaliação Caixa Econômica Federal: planejamento/sites_avaliados/avaliacao_CAIXA.md
                - Avaliação SSALTO: planejamento/sites_avaliados/avaliacao_SSALTO.md
                - Avaliação DETRAN: planejamento/sites_avaliados/avaliacao_DETRANGO.md
          - Sítio Escolhido: planejamento/site_escolhido.md
          - Processo de Design: planejamento/design.md
    - Análise de Requisitos:
          - Aspectos Éticos: analise_requisitos/aspectos_eticos.md
          - Perfil do Usuário: analise_requisitos/perfilUsuario.md
          - Princípios e diretrizes do projeto: analise_requisitos/principios.md
          - Personas: analise_requisitos/personas.md
          - Análise de Tarefas: analise_requisitos/analise_de_tarefas.md
          - Cenários: analise_requisitos/cenarios.md
          - Característica para Plataforma: analise_requisitos/caracteristicas_para_plataforma.md
          - Guia de Estilo: analise_requisitos/guia_estilo.md
          - Mapa de empatia: analise_requisitos/mapa_de_empatia.md
          - Metas de usabilidade: analise_requisitos/metas_de_usabilidade.md
    - Design, Avaliação e Desenvolvimento:
          - Nível 1:
                - Storyboards:
                      - Planejamento da Avaliação: design_avaliacao/nivel1/storyboards/planejamento_avaliacao.md
                      - Planejamento do Relato de Resultados da Análise: design_avaliacao/nivel1/storyboards/planejamento_relato_resultados.md
                      - Relato dos Resultados: design_avaliacao/nivel1/storyboards/storyboard_relato.md
                - Análise de Tarefas:
                      - Planejamento da Avaliação: design_avaliacao/nivel1/analise_tarefas/planejamento_analise_tarefas.md 
                      - Planejamento do Relato de Resultados da Análise: design_avaliacao/nivel1/analise_tarefas/planejamento_relato_resultados.md
                      - Relato dos Resultados: design_avaliacao/nivel1/analise_tarefas/relato_resultados_tarefas.md
          - Nível 2:
                - Protótipo de papel:
                      - Planejamento da Avaliação: design_avaliacao/nivel2/prototipoPapel/planejamentoAvaliacao.md
                      - Planejamento do Relato de Resultados da Análise: design_avaliacao/nivel2/prototipoPapel/planejamentoRelatoResultados.md
    - Verificação:
          - Planejamento da verificação: verificacao/planejamento.md
          - Teste Piloto:
                      - Planejamento: verificacao/teste/planejamento.md
                      - Aspectos gerais: verificacao/teste/aspectos_gerais.md
                      - Processo de design: verificacao/teste/processo_de_design.md
                      - Perfil de usuário: verificacao/teste/perfil_de_usuario.md
                      - Personas: verificacao/teste/personas.md
                      - Aspectos éticos: verificacao/teste/aspectos_eticos.md
                      - Análise de tarefas: verificacao/teste/analise_de_tarefas.md
                      - Metas de usabilidade: verificacao/teste/metas_de_usabilidade.md
                      - Características da Plataforma: verificacao/teste/caract_da_plataforma.md
                      - Princípios gerais de projeto: verificacao/teste/principios_gerais_de_projeto.md
                      - Guia de estilo: verificacao/teste/guia_de_estilo.md
                      - Planejamento da avaliação - Análise de tarefas: verificacao/teste/planejamentoA_tarefas.md
                      - Planejamento do relato - Análise de tarefas: verificacao/teste/planejamentoR_tarefas.md
                      - Relato - Análise de tarefas: verificacao/teste/relato_tarefas.md
                      - Planejamento da avaliação - Storyboard: verificacao/teste/planejamentoA_storyboard.md
                      - Planejamento do relato - Storyboard: verificacao/teste/planejamentoR_storyboard.md
                      - Relato - Storyboard: verificacao/teste/relato_storyboard.md
                      - Planejamento da avaliação - Protótipo de papel: verificacao/teste/planejamentoA_papel.md
                      - Planejamento do relato - Protótipo de papel: verificacao/teste/planejamentoR_papel.md
    - Apresentações:
          - Primeira Etapa: apresentacoes/1a_apresentacao.md
          - Segunda Etapa: apresentacoes/2a_apresentacao.md
          - Terceira Etapa: apresentacoes/3a_apresentacao.md
          - Quarta Etapa: apresentacoes/4a_apresentacao.md
          - Quinta Etapa: apresentacoes/5a_apresentacao.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
